### ISSUE TITLE
Killing ron doesn't kill all child processes

### ISSUE THREAD

**Issue by noonat** [upsight/ron#1]
I noticed when running `ron t test` that a Docker container was left behind after hitting <kbd>CTRL+C</kbd>. It appears that, because ron runs the target's cmd as a bash script, when ron receives a kill signal it kills bash but not bash's child processes. You can reproduce this with this ron.yaml:

``` yaml
targets:
  sleep:
    cmd: |
      sleep 120
```

Run `ron t sleep`, and then send a kill signal to the process. Note that the ron and bash processes have both been killed, but sleep is still running and orphaned.

**Comment by pkar** [comment]
https://github.com/upsight/ron/commit/02385cde2c877a436b021d95b3b57d9840d1449e
